# Generated by Django 4.2.16 on 2024-09-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
    ]
